name: notify-child
on:
  push:
    branches:
      - 'main'
    paths:
      - 'common/**'
      - 'child/**'
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to child repo
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.PAT_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/kfranqueiro/test-childrepo/dispatches \
          -d '{"event_type":"build-from-monorepo"}'
